[package]
name = "preproc"
version = "0.1.0"
authors = ["Tavian Barnes <tavianator@tavianator.com>"]
edition = "2021"

[dependencies]
clap = "3.1.8"
mdbook = "0.4.17"
pulldown-cmark = "0.9.1"
pulldown-cmark-to-cmark = "10.0.1"
serde_json = "1.0.79"
