[package]
name = "preproc"
version = "0.1.0"
authors = ["Tavian Barnes <tavianator@tavianator.com>"]
edition = "2021"

[dependencies]
clap = "3.0.10"
mdbook = "0.4.15"
pulldown-cmark = "0.9.1"
pulldown-cmark-to-cmark = "9.0.0"
serde_json = "1.0.78"
