[package]
name = "preproc"
version = "0.1.0"
authors = ["Tavian Barnes <tavianator@tavianator.com>"]
edition = "2018"

[dependencies]
clap = "2.34.0"
mdbook = "0.4.14"
pulldown-cmark = "0.8.0"
pulldown-cmark-to-cmark = "7.1.1"
serde_json = "1.0.68"
