[book]
authors = ["Tavian Barnes"]
title = "tavianator.com"

[build]
build-dir = "site"

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "navy"
google-analytics = "UA-51266553-1"
no-section-label = true
git-repository-url = "https://github.com/tavianator/tavianator.com"

[output.html.print]
enable = false

[preprocessor.site]
command = "./target/debug/preproc"
renderer = ["html"]
